# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diagnostics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'diagnostics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64iagnostics.proto\x12\x03\x65\x64\x63\"\x07\n\x05\x45mpty\"G\n\x0cSystemStatus\x12\x11\n\tcpu_usage\x18\x01 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x02 \x01(\x02\x12\x0e\n\x06uptime\x18\x03 \x01(\t\"6\n\x0eServiceCommand\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"1\n\rCommandResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\x12\x44iagnosticsService\x12\x30\n\x0fGetSystemStatus\x12\n.edc.Empty\x1a\x11.edc.SystemStatus\x12\x39\n\x0e\x43ontrolService\x12\x13.edc.ServiceCommand\x1a\x12.edc.CommandResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diagnostics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_SYSTEMSTATUS']._serialized_start=35
  _globals['_SYSTEMSTATUS']._serialized_end=106
  _globals['_SERVICECOMMAND']._serialized_start=108
  _globals['_SERVICECOMMAND']._serialized_end=162
  _globals['_COMMANDRESULT']._serialized_start=164
  _globals['_COMMANDRESULT']._serialized_end=213
  _globals['_DIAGNOSTICSSERVICE']._serialized_start=216
  _globals['_DIAGNOSTICSSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
