# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import diagnostics_pb2 as diagnostics__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in diagnostics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiagnosticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
                '/edc.DiagnosticsService/GetSystemStatus',
                request_serializer=diagnostics__pb2.Empty.SerializeToString,
                response_deserializer=diagnostics__pb2.SystemStatus.FromString,
                _registered_method=True)
        self.ControlService = channel.unary_unary(
                '/edc.DiagnosticsService/ControlService',
                request_serializer=diagnostics__pb2.ServiceCommand.SerializeToString,
                response_deserializer=diagnostics__pb2.CommandResult.FromString,
                _registered_method=True)


class DiagnosticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagnosticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=diagnostics__pb2.Empty.FromString,
                    response_serializer=diagnostics__pb2.SystemStatus.SerializeToString,
            ),
            'ControlService': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlService,
                    request_deserializer=diagnostics__pb2.ServiceCommand.FromString,
                    response_serializer=diagnostics__pb2.CommandResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edc.DiagnosticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edc.DiagnosticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiagnosticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edc.DiagnosticsService/GetSystemStatus',
            diagnostics__pb2.Empty.SerializeToString,
            diagnostics__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edc.DiagnosticsService/ControlService',
            diagnostics__pb2.ServiceCommand.SerializeToString,
            diagnostics__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
